server:
  port: 9010
spring:
  application:
    name: xuxian-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xianyu122/xuxian_config.git
  rabbitmq:
    host: 120.26.89.104
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh